# Generated by Django 5.0.6 on 2025-07-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="has_toast",
            field=models.BooleanField(
                blank=True, help_text="Does this place serve toast?", null=True
            ),
        ),
    ]
